robot:
  id: xlerobot
  port_left_base: /dev/ttyACM1
  port_right_head: /dev/ttyACM0
  left_arm_id: left_follower_arm
  right_arm_id: right_follower_arm
  max_relative_target: 8.0
  use_degrees: true
  home_pose:
    left_arm_shoulder_pan: 22.0220
    left_arm_shoulder_lift: -76.5714
    left_arm_elbow_flex: 78.5934
    left_arm_wrist_flex: 8.2198
    left_arm_wrist_roll: -5.4066
    left_arm_gripper: 0.5559
    right_arm_shoulder_pan: -34.3736
    right_arm_shoulder_lift: -81.2747
    right_arm_elbow_flex: 84.0440
    right_arm_wrist_flex: 15.5604
    right_arm_wrist_roll: 5.4066
    right_arm_gripper: 0.6241
cameras:
  head:
    type: opencv
    path: /dev/v4l/by-path/pci-0000:0e:00.0-usb-0:3:1.0-video-index0
    fps: 30
    width: 640
    height: 480
    fourcc: MJPG
  right_wrist:
    type: opencv
    path: /dev/v4l/by-path/pci-0000:0e:00.0-usb-0:4.4:1.0-video-index0
    fps: 30
    width: 640
    height: 480
    fourcc: MJPG
  left_wrist:
    type: opencv
    path: /dev/v4l/by-path/pci-0000:0e:00.0-usb-0:4.1:1.0-video-index0
    fps: 30
    width: 640
    height: 480
    fourcc: MJPG
dataset:
  repo_id: saivishwak/xlerobot-vr-pick-place-pen
  home_before_episode: true
  fps: 30
  push_to_hub: false
  root: ~/.cache/huggingface/lerobot/saivishwak/xlerobot-vr-pick-place-pen
pi05:
  server_host: 127.0.0.1
  server_port: 8000
  action_horizon: 50
  control_fps: 30
vr:
  kp: 0.75
  homing_present_tolerance_deg: 4.0
  pos_ema_alpha: 0.22
  pos_deadzone_m: 0.002
  max_ee_step_m: 0.003
  quest_video:
    roles:
    - head
    - left_wrist
    - right_wrist
    base_port: 5600
    bitrate_kbps: 2500
    flip_method: rotate-180
    brightness: 0.0
    contrast: 1.0
    saturation: 1.0
  wrist_motor_polarity:
    left:
      flex: -1
      roll: 1
    right:
      flex: -1
      roll: 1
  joint_deg_caps:
    shoulder_pan: 5.0
    shoulder_lift: 5.0
    elbow_flex: 5.0
    wrist_flex: 6.0
    wrist_roll: 10.0
    gripper: 15.0
  joint_command_deadband_deg:
    shoulder_pan: 0.18
    shoulder_lift: 0.18
    elbow_flex: 0.18
    wrist_flex: 0.25
    wrist_roll: 0.25
    gripper: 0.0
  joint_command_filter_weights:
  - 0.4
  - 0.3
  - 0.2
  - 0.1
gripper:
  open_value: 0
  closed_value: 100
